### ISSUE TITLE
whamp output parameter RI complex or real?

### ISSUE THREAD

**Issue by thomas-nilsson-irfu** [irfu/whamp#2]
Dear **whamp** community,

During the last few days I have made some very minor changes here in the whamp repository as part of preparations for getting new compiled mex files (see details in irfu/irfu-matlab#61). And as part of this I wanted to understand the inputs & outputs of these compiled mex files when I noticed what to me appears to a minor bug/typo:

- Output `RI` should be complex or real?
https://github.com/irfu/whamp/blob/08ced3cfa3f91b665d6376705467358f299c3a50/src/comcout.f90#L19 According to the official [WHAMP report](https://github.com/irfu/whamp/blob/master/WHAMP_Report_1982.pdf) page 43 the output `RI = kc/w refractive index (COMPLEX)`, and on the following page 44 it was originally in the report quoted code given as `complex`. But looking at the code here in this repository it has as far as I can see only ever been given as `real`. Even looking at the very first commit:
https://github.com/irfu/whamp/blob/7be0ffd5356b108d76d2ede6d8e2bbba2ab3d1a8/WHAMP_code/comcout.h#L5-L8
Is this a bug in the code? Or was it changed from the time of publication of this report (before the repository here was created)?
It was apparently simply silenced by hard-coding it to `real` in: https://github.com/irfu/whamp/commit/814716aae2c89f4612d81c109d4d2998092abd41#diff-70ce068239fc9ffb7ebfc84baf08cd2865b48cdc2ab7e0b3e1d96de4a7fc23d9R105, but I would like to really know which is the correct data type for this output parameter.

Footnote: I do not think I had heard of [complex refractive index](https://en.wikipedia.org/wiki/Refractive_index#Complex_refractive_index) before, but apparently it is a thing...

--
With best regards,
Thomas Nilsson

**Comment by thomas-nilsson-irfu** [comment]
Just adding a note here, mainly to keep track of my finding so far in regards to this issue.

The old archive files do not provide too much insight into when this was changed, but some information can at least be derived...

The old included archive file `Archive/WHAMP_code_77.zip` contain:
- comcout.h
```
7:      COMMON /COUT/ X, P, Z, EFL, BFL ,D, DX, DZ, DP, E, 
8:     +              VG(2),SG(2),RI(2),ENE
```
and
- whamp.f
```
8:      COMPLEX*16 X,XO,XVO,XX(10),XP(10),DX,OME,FPX,DIR,DIX,DIZ,DIP,
9:     * EPS(6,4),DOX,DOZ,DOP,CX,EFL(3),BFL(3),RI
...
14:      COMMON /COUT/ X,P,Z,EFL,BFL,DIR,DIX,DIZ,DIP,EPS,VG(2),SG(2),RI,ENE
```
While the other old archive file `Archive/WHAMP.tar.gz_original` contain:
- comcout.h
```
5:      COMMON /COUT/ X, P, Z, EFL, BFL ,D, DX, DZ, DP, E,
6:     c       VG(2), SG(2), RI(2), ENE
```
and
- whamp.f
```
6:      COMPLEX*16 X,XO,XVO,XX(6),XP(6),DX,OME,FPX,DIR,DIX,DIZ,DIP,
7:     * EPS(6,4),DOX,DOZ,DOP,CX,EFL(3),BFL(3),RI
...
11:     C   DN(6),TA(6),XP,CV,PM(3),ZM(3),XOI,XC,PZL,JMA 
12:      COMMON /COUT/ X,P,Z,EFL,BFL,DIR,DIX,DIZ,DIP,EPS,VG(2),SG(2),RI,ENE
```

So it appears the latest "official" files from Kjell Rönnmark at least had this `RI` as complex.

The archives also contain a file `WHAMP_error_log` which appears to be a sort of change log file, (Note to self: keep that in mind if some other questions arise about discrepancies between the paper and the code).

However this `WHAMP_error_log` file contain one huge disclaimer (meaning it will not be of help for this particular issue):
> The main exception is that changes and additions to the main program
> and the input/output routines (TYPIN and OUTPT) are not included in the 
> error log.

**Comment by vaivads** [comment]
Good point. It is ok to change back to RI complex to be consistent with the report. The reason RI was made real is to have it's physical interpretation as the inverse of phase velocity. By going to complex notation this interpretation is not anymore technically correct even though for low damping waves it is still a very good approximation. RI is very seldom used by scientists, in plasma physics usually one sticks to k and omega. 
Note that the example of complex refraction index that you refer to has complex k. In WHAMP  notation is to have k always real and omega complex.
